# 8.异常

## 1.异常体系

**Java 异常类层次结构图概览** 

![image-20230413192439101](img.assets\image-20230413192439101.png)

- Java中异常继承的根类是：`Throwable`

Exception异常的分类：

1. **编译时异常**：继承自`Exception`的异常或者其子类，编译阶段就会报错
2. **运行时异常**：继承自`RuntimeException`的异常或者其子类，编译阶段不报错，但是运行阶段报错

![异常的分类](img.assets\异常的分类.png)



### 1.1.Exception和Error的区别

在 Java 中，所有的异常都有一个共同的祖先 `java.lang` 包中的 `Throwable` 类。`Throwable` 类有两个重要的子类:

- **`Exception`** :程序本身可以处理的异常，可以通过 `catch` 来进行捕获。`Exception` 又可以分为 Checked Exception (受检查异常，必须处理) 和 Unchecked Exception (不受检查异常，可以不处理)。
- **`Error`** ：`Error` 属于程序无法处理的错误 ，我们不建议通过`catch`捕获 。例如 Java 虚拟机运行错误（`Virtual MachineError`）、虚拟机内存不够错误(`OutOfMemoryError`)、类定义错误（`NoClassDefFoundError`）等 。这些异常发生时，Java 虚拟机（JVM）一般会选择线程终止

> 在理论上可以使用 `catch` 语句来捕获 `Error` 类的对象，但这并不是一种推荐的做法。通常情况下，对于 `Error` 类的错误，应该通过更好的方式，例如日志记录和告警通知等，进行适当的处理，而不是尝试恢复程序的执行。



### 1.2 Checked Exception和Unchecked Exception的区别

在Java中，异常（Exception）分为两种类型：已检查异常（Checked Exception）和未检查异常（Unchecked Exception）



#### 1.2.1 Checked Exception

**Checked Exception** 即受检查异常 ，Java代码在编译过程中，如果受检查异常没有被`catch`或者`throws` 关键字处理的话，就没办法通过编译。

在Java中，所有继承自`java.lang.Exception`类（除了`RuntimeException`及其子类）的异常都属于受检查异常。

常见的受检查异常有： IO 相关的异常、`ClassNotFoundException` 、`SQLException`...。



#### 1.2.2 Unchecked Exception

未检查异常是在运行时发生的异常，不需要在编码时显式处理的异常。在Java中，所有继承自`java.lang.RuntimeException`及其子类的异常都属于未检查异常。这些异常通常表示了编程错误或者其他无法预料的运行时错误，例如空指针引用（`NullPointerException`）、数组越界（`ArrayIndexOutOfBoundsException`）等。因为不需要显式处理，所以在代码中可以不使用`try-catch`块进行捕获处理，也可以不在方法的声明中使用`throws`关键字声明该异常。



`RuntimeException` 及其子类都统称为非受检查异常，常见的有：

> `NullPointerException`(空指针错误)
>
> `IllegalArgumentException`(参数错误比如方法入参类型错误)
>
> `NumberFormatException`（字符串转换为数字格式错误，`IllegalArgumentException`的子类）
>
> `ArrayIndexOutOfBoundsException`（数组越界错误）
>
> `ClassCastException`（类型转换错误）
>
> `ArithmeticException`（算术错误）
>
> `SecurityException` （安全错误比如权限不够）
>
> `UnsupportedOperationException`(不支持的操作错误比如重复创建同一用户)



## 2.Throwable类中的常用方法

- `String getMessage()`: 返回异常发生时的简要描述

- `String toString()`: 返回异常发生时的详细信息

- `String getLocalizedMessage()`: 返回异常对象的本地化信息。使用 `Throwable` 的子类覆盖这个方法，可以生成本地化信息。如果子类没有覆盖该方法，则该方法返回的信息与 `getMessage()`返回的结果相同

- `void printStackTrace()`: 在控制台上打印 `Throwable` 对象封装的异常信息



## 3.异常的处理

Java异常处理的五个关键字：**try、catch、finally、throw、throws**



### 3.1 抛出异常throw

在java中，提供了一个**`throw`**关键字，它用来抛出一个指定的异常对象。

throw**用在方法内**，用来抛出一个异常对象，将这个异常对象传递到`调用者`处，并结束当前方法的执行。

**使用格式：**

```java
throw new 异常类名(参数);
```

> 如果抛出的异常时`受检查型异常`,则需要手动进行处理

```java
    //未检测异常
	public void test() {
        throw new NullPointerException();
    }
    //受检查异常
    public void test1() throws ClassNotFoundException {
        throw new ClassNotFoundException();
    }
```



### 3.2 声明异常throws

关键字**`throws`**运用于方法声明之上,用于表示当前方法不处理异常,而是提醒该方法的`调用者`来处理异常(抛出异常)。

**声明异常格式：**

```java
修饰符 返回值类型 方法名(参数) throws 异常类名1,异常类名2…{   }	
```



### 3.3 异常捕获try-catch-finally

`try`块 ：用于捕获异常。其后可接零个或多个 `catch` 块，如果没有 `catch` 块，则必须跟一个 `finally` 块。

`catch`块 ：用于处理 try 捕获到的异常。

`finally` 块 ：无论是否捕获或处理异常，`finally` 块里的语句都会被执行。当在 `try` 块或 `catch` 块中遇到 `return` 语句时，`finally` 语句块将在方法返回之前被执行。

```java
try{
     编写可能会出现异常的代码
}catch(异常类型A  e){  当try中出现A类型异常,就用该catch来捕获.
     处理异常的代码
     //记录日志/打印异常信息/继续抛出异常
}catch(异常类型B  e){  当try中出现B类型异常,就用该catch来捕获.
     处理异常的代码
     //记录日志/打印异常信息/继续抛出异常
}finally{
    //都需要执行
}
```

#### 3.3.1 finally注意事项

>**`不要在 finally 语句块中使用 return!`**当 try 语句和 finally 语句中都有return语句时，try 语句块中的 return 语句会被忽略。这是因为try语句中的return返回值会先被暂存在一个`本地变量`中，当执行到 finally 语句中的 return 之后，这个本地变量的值就变为了finally语句中的 return 返回值。

JVM官方解释:

如果try语句里有return，返回的是try语句块中变量值。 
详细执行过程如下：

a.如果有返回值，就把返回值保存到局部变量中；

b.执行jsr指令跳到finally语句里执行；

c.执行完finally语句后，返回之前保存在局部变量表里的值。

**如果try，finally语句里均有return，忽略try的return，而使用finally的return**。



#### 3.3.2 finally中的代码一定会执行吗?

不一定的！在某些情况下，finally中的代码不会被执行。

`finally`块的代码不会被执行情况：

1. 程序所在的线程死亡。
2. 关闭 CPU。
3. finally之前虚拟机被终止运行。



#### 3.3.3 try-with-resources

**适用范围（资源的定义）：** 任何实现 `java.lang.AutoCloseable`或者 `java.io.Closeable` 的对象

**关闭资源和 finally 块的执行顺序：** 在 `try-with-resources` 语句中，任何 catch 或 finally 块在声明的资源关闭后运行

```java
public interface Closeable extends AutoCloseable {
    public void close() throws IOException;
}
```

《Effective Java》中明确指出：

>面对必须要关闭的资源，我们总是应该优先使用 `try-with-resources` 而不是`try-finally`。随之产生的代码更简短，更清晰，产生的异常对我们也更有用。`try-with-resources`语句让我们更容易编写必须要关闭的资源的代码，若采用`try-finally`则几乎做不到这点。

Java 中类似于`InputStream`、`OutputStream` 、`Scanner` 、`PrintWriter`等的资源都需要我们调用`close()`方法来手动关闭，一般情况下我们都是通过`try-catch-finally`语句来实现这个需求，如下：

```java
try (Scanner scanner = new Scanner(new File("test.txt"))) {
    while (scanner.hasNext()) {
        System.out.println(scanner.nextLine());
    }
} catch (FileNotFoundException fnfe) {
    fnfe.printStackTrace();
}
```

通过使用分号分隔，可以在`try-with-resources`块中声明多个资源。

```java
try (BufferedInputStream bin = new BufferedInputStream(new FileInputStream(new File("test.txt")));
     BufferedOutputStream bout = new BufferedOutputStream(new FileOutputStream(new File("out.txt")))) {
    int b;
    while ((b = bin.read()) != -1) {
        bout.write(b);
    }
}
catch (IOException e) {
    e.printStackTrace();
}
```



## 4.使用异常注意事项

- 不要把异常定义为静态变量，因为这样会导致异常栈信息错乱。每次手动抛出异常，我们都需要手动 new 一个异常对象抛出。

- 抛出的异常信息一定要有意义。

- 建议抛出更加具体的异常比如字符串转换为数字格式错误的时候应该抛出`NumberFormatException`而不是其父类`IllegalArgumentException`。

- 使用日志打印异常之后就不要再抛出异常了（两者不要同时存在一段代码逻辑中）。
- 如果父类抛出了多个异常,子类覆盖父类方法时,只能抛出相同的异常或者是他的子集。
- 父类方法没有抛出异常，子类覆盖父类该方法时也不可抛出异常。此时子类产生该异常，只能捕获处理，不能声明抛出
- 当多异常处理时，捕获处理，前边的类不能是后边类的父类